### ISSUE TITLE
I don't know how to evaluate this project

### ISSUE THREAD

**Issue by MichaelKentBurns** [efatha/pastry.nas#2]
Since you did not provide a README.md file I don't know what you are trying to demonstrate with this project.

Yes, it makes a pretty page with pictures but it's all just boiler plate stuff pasted in.
It still has a lot of 'Lorem ipsum' latin. 
Your title 'My Food' is not meaningful.
Your titles under each picture has nothing to do with the picture.   

Your goal should be to demonstrate your ability to make a meaningful and functional web page. 
Take the time to make it more real.    

The reason I say this is that since you link to your GitHub page from your Upwork portfolio, you might expect that prospective clients will look at it.   If they do, and see this repository they might conclude that you like to start things but not finish them.  

If you just want to show me something, or get feedback as you work on a project, you might choose to go into the settings of that repository and make it private rather than public.   When it is private, you have the ability to invite me to collaborate with you on the project.  That way, I can review it and add issues like this but it won't be visible to the public.   

Since you submitted this to me as a challenge, I assume you want it evaluated.   
My evaluation is that it is not complete.

**Comment by efatha** [comment]
I everything is all set by now. Resolved the issue by changing the "lorem ... " Latin words into meaningful syntaxes , changed the title and brought some modification in order to reach the goal of my website. Made some good semantic structures to push  the user on having so much attention by reading this site.
